from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1]))

from backend.app.services.statement_parser import (
    _detect_pdf_provider,
    _extract_axis_transactions,
    _extract_bank_of_baroda_transactions,
    _extract_bhim_transactions,
    _extract_google_pay_transactions,
    _extract_hdfc_transactions,
    _extract_icici_transactions,
    _extract_paytm_transactions,
    _extract_phonepe_transactions,
    _extract_sbi_transactions,
)


def test_detect_supported_providers():
    assert _detect_pdf_provider("PhonePe transaction statement") == "phonepe"
    assert _detect_pdf_provider("Google Pay transaction history") == "google_pay"
    assert _detect_pdf_provider("Paytm Payments Bank account statement") == "paytm"
    assert _detect_pdf_provider("BHIM UPI statement generated by NPCI") == "bhim"
    assert _detect_pdf_provider("State Bank of India account statement") == "sbi"
    assert _detect_pdf_provider("Bank of Baroda statement") == "bank_of_baroda"
    assert _detect_pdf_provider("HDFC Bank account statement") == "hdfc"
    assert _detect_pdf_provider("ICICI Bank statement") == "icici"
    assert _detect_pdf_provider("Axis Bank statement") == "axis"


def test_phonepe_extractor():
    lines = [
        "PhonePe Transaction Statement",
        "01 Jun 2026",
        "09:12 AM",
        "Paid to Swiggy",
        "swiggy@ibl",
        "PhonePe Transaction ID: PP123456789",
        "UTR: 123456789012",
        "INR 420.00",
        "SUCCESS",
    ]

    transactions = _extract_phonepe_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 420.0
    assert transactions[0]["merchant"] == "Swiggy"


def test_google_pay_extractor():
    lines = [
        "Google Pay statement",
        "02 Jun 2026 10:45 PM",
        "Paid to Amazon Pay",
        "amazonpay@apl",
        "Google transaction ID: 987654321ABC",
        "UPI transaction ID: 123456789123",
        "Amount INR 850.00",
        "SUCCESS",
    ]

    transactions = _extract_google_pay_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 850.0
    assert transactions[0]["merchant"] == "Amazon Pay"


def test_paytm_extractor():
    lines = [
        "Paytm UPI statement",
        "03/06/2026 20:15",
        "Money sent to Jio Recharge",
        "jio@paytm",
        "UPI Ref No: 202606030001",
        "Rs. 199.00",
        "SUCCESS",
    ]

    transactions = _extract_paytm_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 199.0
    assert transactions[0]["merchant"] == "Jio Recharge"


def test_bhim_extractor():
    lines = [
        "BHIM UPI history",
        "04 Jun 2026",
        "08:05 PM",
        "Paid to Flipkart",
        "flipkart@axis",
        "Txn ID: BHIM123456",
        "UTR: 444455556666",
        "INR 1200.00",
        "SUCCESS",
    ]

    transactions = _extract_bhim_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 1200.0
    assert transactions[0]["merchant"] == "Flipkart"


def test_sbi_bank_extractor():
    lines = [
        "State Bank of India Statement",
        "05/06/2026  UPI/SWIGGY/UTR123456789  650.00  0.00  12000.00",
    ]

    transactions = _extract_sbi_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 650.0


def test_bank_of_baroda_extractor():
    lines = [
        "Bank of Baroda Statement",
        "06/06/2026  UPI AMAZONPAY REF123456  499.00  0.00  11501.00",
    ]

    transactions = _extract_bank_of_baroda_transactions(lines, "\n".join(lines))

    assert len(transactions) == 1
    assert transactions[0]["amount"] == 499.0


def test_hdfc_icici_axis_extractors():
    hdfc_lines = [
        "HDFC Bank Statement",
        "07/06/2026  UPI BIGBASKET HDFC123456  275.00  0.00  11226.00",
    ]
    icici_lines = [
        "ICICI Bank Statement",
        "08/06/2026  UPI MYNTRA ICICI654321  999.00  0.00  10227.00",
    ]
    axis_lines = [
        "Axis Bank Statement",
        "09/06/2026  UPI IRCTC AXIS999888  1499.00  0.00  8728.00",
    ]

    assert _extract_hdfc_transactions(hdfc_lines, "\n".join(hdfc_lines))[0]["amount"] == 275.0
    assert _extract_icici_transactions(icici_lines, "\n".join(icici_lines))[0]["amount"] == 999.0
    assert _extract_axis_transactions(axis_lines, "\n".join(axis_lines))[0]["amount"] == 1499.0
