"""Build a SYNTHETIC UPI statement for demonstrating the risk engine.

Why this exists
---------------
Showing the system working needs a statement with fraud in it. A real one
cannot be used: it carries a real phone number, a real card tail and the
names of real people who never agreed to appear in a project demo. So this
generates one instead, and the output says on every page that it is generated
test data rather than a record of any account.

What it produces
----------------
    docs/demo/DEMO_UPI_Statement.pdf   in the wallet-statement layout the
                                       parser reads, ~3 months of traffic
    docs/demo/DEMO_UPI_Statement.csv   the same rows, for any path that takes
                                       a CSV instead
    docs/demo/DEMO_ANSWER_KEY.md       which rows are planted, and which check
                                       is meant to fire on each

The legitimate traffic is not filler. It is what makes the planted rows
detectable at all: the engine scores a payment against the payer's OWN
history, so a demo statement with no established habits gives every feature
nothing to compare against. That is why this builds ~3 months of canteen
payments, a monthly rent, repeat friends and an autopay before it plants
anything.

    python scripts/make_demo_statement.py
"""

from __future__ import annotations

import csv
import json
import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "demo"

# A fictional account. Not a real number, not a real card.
ACCOUNT = "9000000000"
CARD_TAIL = "XXXXXX4242"
# The period ends today and runs back 92 days. This matters: the reputation
# store measures a payee's age against the clock at the moment of the check,
# so a statement pinned to fixed dates would show a "four-day-old" address as
# four months old by the time anyone demonstrates it. Regenerate the file and
# the dates move with you.
TODAY = datetime.now().replace(hour=21, minute=0, second=0, microsecond=0)
END = TODAY
START = (TODAY - timedelta(days=92)).replace(hour=0, minute=0)
SEED = 2026

BANNER = "SYNTHETIC DEMO DATA - GENERATED BY scripts/make_demo_statement.py - NOT A REAL ACCOUNT"

# DejaVu carries the rupee sign and the Cyrillic block. Both matter: the
# amounts need the first, and the planted lookalike payee needs the second.
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
FONTS = {
    "Demo": FONT_DIR / "DejaVuSans.ttf",
    "Demo-Bold": FONT_DIR / "DejaVuSans-Bold.ttf",
}


@dataclass
class Tx:
    when: datetime
    counterparty: str
    vpa: str
    amount: float
    direction: str                  # DEBIT | CREDIT
    autopay: bool = False
    planted: str = ""               # empty for legitimate traffic
    tags: list[str] = field(default_factory=list)


def _ref(rng: random.Random, prefix: str, n: int) -> str:
    return prefix + "".join(str(rng.randint(0, 9)) for _ in range(n))


# ── The payer's ordinary life ────────────────────────────────────────────────
# Every payee here is invented. The point of the mix is to give the engine a
# baseline with real shape: a few payees paid constantly (high pair count,
# high repeat ratio), a genuine large recurring payment so that "large" alone
# is not suspicious, and credits so the account is not one-directional.

def legitimate(rng: random.Random) -> list[Tx]:
    """Three months of ordinary traffic for a salaried adult.

    The spending level is chosen, not incidental. The model was trained on a
    population whose median payment is around ₹270, and the amount feature it
    reads is the payment divided by the payer's OWN median. A persona whose
    median is ₹25 - all ten-rupee autopays and twenty-rupee tea - pushes every
    ratio an order of magnitude outside the range the model ever saw, and the
    scores come back flat. So this persona buys groceries, takes cabs and pays
    rent, and lands near ₹300.
    """
    rows: list[Tx] = []
    day = START

    def at(d: datetime, h: int, m_lo: int, m_hi: int) -> datetime:
        return d.replace(hour=h, minute=rng.randint(m_lo, m_hi), second=0, microsecond=0)

    while day <= END:
        weekday = day.weekday()

        # Office cafeteria, most working days.
        if weekday < 5 and rng.random() < 0.85:
            rows.append(Tx(at(day, rng.choice([9, 13, 13, 16]), 0, 59), "SRI LAKSHMI CANTEEN",
                           "srilakshmi.canteen@ybl",
                           rng.choice([45, 60, 75, 90, 110, 120, 140]), "DEBIT"))

        # Groceries and the neighbourhood store.
        if rng.random() < 0.55:
            name, vpa = rng.choice([
                ("FRESHMART SUPERSTORE", "freshmart.store@ibl"),
                ("SRI VENKATESWARA KIRANA", "svkirana@paytm"),
            ])
            rows.append(Tx(at(day, rng.choice([18, 19, 20]), 0, 59), name, vpa,
                           round(rng.uniform(160, 940), 2), "DEBIT"))

        # Cabs and autos.
        if rng.random() < 0.62:
            rows.append(Tx(at(day, rng.choice([8, 9, 18, 19, 21]), 0, 59), "METRO RIDE MOBILITY",
                           "metroride.trips@ibl", round(rng.uniform(58, 265), 2), "DEBIT"))

        # Food delivery a few evenings a week.
        if rng.random() < 0.36:
            rows.append(Tx(at(day, 20, 0, 59), "QUICKBITE FOODS PRIVATE LIMITED",
                           "quickbite.foods@ibl", round(rng.uniform(149, 465), 2), "DEBIT"))

        # Chemist / medical store, occasionally.
        if rng.random() < 0.1:
            rows.append(Tx(at(day, rng.randint(10, 20), 0, 59), "SAI MEDICALS",
                           "saimedicals@ybl", round(rng.uniform(85, 620), 2), "DEBIT"))

        # Friends and family, both directions. These build the repeat-payer
        # shape that separates a real counterparty from a one-shot one.
        if rng.random() < 0.38:
            name, vpa = rng.choice([
                ("RAVI TEJA K", "raviteja.k@oksbi"),
                ("SNEHA P", "sneha.p@ybl"),
                ("ARJUN M", "arjun.m@paytm"),
                ("DEEPTHI R", "deepthi.r@axl"),
            ])
            out = rng.random() < 0.55
            rows.append(Tx(at(day, rng.randint(11, 21), 0, 59), name, vpa,
                           rng.choice([100, 150, 200, 250, 300, 500, 800, 1200]),
                           "DEBIT" if out else "CREDIT"))

        # Fuel, roughly weekly.
        if weekday == 5 and rng.random() < 0.75:
            rows.append(Tx(at(day, 17, 0, 50), "METROFUEL PUMP 42",
                           "metrofuel42@ibl", round(rng.uniform(600, 1450), 2), "DEBIT"))

        # Rail tickets now and then.
        if rng.random() < 0.06:
            rows.append(Tx(at(day, rng.randint(9, 22), 0, 59), "IRCTC TICKETING",
                           "irctc.tickets@sbi", round(rng.uniform(240, 860), 2), "DEBIT"))

        # ── Monthly anchors ──────────────────────────────────────────────
        # Rent. This is the row that stops "large amount" from being a proxy
        # for fraud: the payer genuinely sends five figures every month, so
        # F3 has to be caught on who is paid and when, not merely on size.
        if day.day == 3:
            rows.append(Tx(at(day, 10, 0, 40), "K RAMANA RAO",
                           "ramanarao.k@oksbi", 18500, "DEBIT"))
        if day.day == 5:
            rows.append(Tx(at(day, 19, 0, 50), "AXIS POWER UTILITY",
                           "axispower.utility@axl", round(rng.uniform(980, 2240), 2), "DEBIT"))
        if day.day == 7:
            rows.append(Tx(at(day, rng.choice([7, 8, 9]), 0, 59), "CLOUDNOTE SUBSCRIPTION",
                           "cloudnote.sub@ybl", 199, "DEBIT", autopay=True))
        if day.day == 9:
            rows.append(Tx(at(day, rng.choice([7, 8]), 0, 59), "SIP AUTOSAVE PLAN",
                           "sipautosave@ybl", 2500, "DEBIT", autopay=True))
        if day.day == 12:
            rows.append(Tx(at(day, rng.randint(10, 19), 0, 59), "BROADBAND FIBRENET",
                           "fibrenet.billing@axl", 799, "DEBIT"))
        if day.day == 1:
            rows.append(Tx(at(day, 11, 0, 30), "VERTEX SOFTWARE SOLUTIONS",
                           "vertexsoft.payroll@icici", 48000, "CREDIT"))

        day += timedelta(days=1)

    return rows


# ── The planted rows ─────────────────────────────────────────────────────────
# One block per attack the report describes, so a judge can be shown the
# mechanism rather than a single undifferentiated "fraud" flag.

def planted() -> list[Tx]:
    """The compromise. Three months of ordinary traffic, then a bad week.

    Every event is placed relative to today rather than on a fixed date, so
    that when the reputation store is asked how old one of these addresses is
    it answers in days, not months. Clustering them at the end is also what
    the real thing looks like: an account is fine until it is not.
    """
    rows: list[Tx] = []

    def d(days_ago: int, hh: int, mm: int) -> datetime:
        return (TODAY - timedelta(days=days_ago)).replace(hour=hh, minute=mm, second=0,
                                                          microsecond=0)

    # F1 - probe burst. A tested credential: a run of tiny payments to
    # addresses never paid before, inside half an hour, at 2am. Caught on
    # velocity, hour familiarity and an all-new payee set.
    for i in range(8):
        rows.append(Tx(d(6, 2, 14) + timedelta(minutes=3 * i),
                       f"VERIFY0{i + 1} SERVICES", f"verify0{i + 1}@quickpay",
                       [1, 2, 5, 9, 14, 21, 33, 47][i], "DEBIT",
                       planted="F1", tags=["velocity", "night", "all payees new"]))

    # F2 - funnel account. One address opened days earlier taking a rapid
    # series of one-shot payments and returning nothing. Caught entirely from
    # the payee side: the payer behaves normally throughout.
    for i in range(5):
        rows.append(Tx(d(4, 18, 2) + timedelta(minutes=11 * i),
                       "QUICKCASH AGENCY", "quickcash.agency@fastpay", 4500, "DEBIT",
                       planted="F2", tags=["payee 3 days old", "no repeat payers", "burst"]))

    # F3 - hijacked profile. Someone else is operating the account: three
    # payments in eleven minutes, each far above anything this payer sends, at
    # an hour they have never used, to addresses they have never paid.
    #
    # This was one lone payment at first, and it was the wrong shape. A
    # takeover empties an account while the access lasts; it does not send one
    # transfer and go to bed. The single-row version only scored because the
    # payee had two payers and a repeat ratio of 0.0 - an empty sample that
    # happens to look identical to a collection account - so the demo was
    # leaning on a number that should never have been decisive, and it fell
    # over the moment thin samples stopped being trusted. Velocity is what
    # actually identifies this scenario, and now the rows carry it.
    for i, (mins, amount, payee, vpa) in enumerate([
        (0, 49500, "NEHRU TRADERS ENTERPRISE", "nehru.traders99@fastpay"),
        (5, 92400, "NEHRU TRADERS ENTERPRISE", "nehru.traders99@fastpay"),
        (11, 38750, "RK GENERAL SUPPLIES", "rk.supplies77@fastpay"),
    ]):
        rows.append(Tx(d(3, 3, 47) + timedelta(minutes=mins), payee, vpa, amount, "DEBIT",
                       planted="F3", tags=["amount vs own median", "night",
                                           "three transfers in eleven minutes"]))

    # F4 - victim-authorised transfer. The class the behavioural model is
    # weakest on, and the reason the other channels exist. Ordinary hour,
    # amount within reach of this payer's rent, new payee. The 1 rupee credit
    # thirteen minutes earlier is the refund-scam opening: a token payment to
    # prove the "refund" works before the real ask.
    rows.append(Tx(d(2, 11, 19), "ELECTRICITY BILL DESK", "electricity.billdesk@upiservice",
                   1, "CREDIT", planted="F4", tags=["token credit", "refund-scam opening"]))
    rows.append(Tx(d(2, 11, 32), "ELECTRICITY BILL DESK", "electricity.billdesk@upiservice",
                   18000, "DEBIT",
                   planted="F4", tags=["new payee", "no behavioural anomaly at all"]))

    # F5 - lookalike address. The handle is @yb1, digit one, against the real
    # @ybl, letter ell. In the sans-serif face every payment app renders a VPA
    # in, those two glyphs are all but identical. The local part then pairs a
    # bank's name with the word "refund", which no bank handle ever does.
    #
    # A Cyrillic homoglyph was tried here first and is the wrong choice for a
    # demo: the character fails the UPI ID validity check before the brand
    # comparison runs, so it reports as malformed - correct, and blocking, but
    # it does not show the machinery. This address scores 100 on two separate
    # critical findings and names the bank it is imitating.
    rows.append(Tx(d(1, 19, 21), "HDFC BANK REFUND CELL", "hdfcbank.refund@yb1",
                   47500, "DEBIT",
                   planted="F5", tags=["confusable handle @yb1 vs @ybl",
                                       "bank name paired with 'refund'"]))

    return rows


# ── Counterparty reputation ─────────────────────────────────────────────────
# The statement gives the engine one payer's side of each edge. The payee half
# - how old an address is, how many OTHER people have paid it, how many of
# them came back - lives in the reputation store, and a single imported
# statement cannot supply it. This describes the crowd around each payee so
# scripts/bootstrap_payee_reputation.py --demo-statement can lay it down.
#
# It is the difference between the funnel account scoring 0.05 and 0.74: what
# makes it a funnel is not that this payer paid it five times, it is that
# forty other people each paid it once and none came back.

PAYEE_CROWD = [
    # vpa, display, age days, other payers, payments each, amount
    ("srilakshmi.canteen@ybl",    "SRI LAKSHMI CANTEEN",        900,  60,  9,   85),
    ("freshmart.store@ibl",       "FRESHMART SUPERSTORE",      1240,  95,  7,  520),
    ("svkirana@paytm",            "SRI VENKATESWARA KIRANA",    810,  48,  8,  310),
    ("metroride.trips@ibl",       "METRO RIDE MOBILITY",       1500, 180, 11,  145),
    ("quickbite.foods@ibl",       "QUICKBITE FOODS",           1120, 150,  8,  290),
    ("saimedicals@ybl",           "SAI MEDICALS",               960,  40,  5,  260),
    ("metrofuel42@ibl",           "METROFUEL PUMP 42",         1350, 120, 10,  900),
    ("irctc.tickets@sbi",         "IRCTC TICKETING",           2200, 300,  4,  480),
    ("axispower.utility@axl",     "AXIS POWER UTILITY",        2400, 260, 12, 1400),
    ("fibrenet.billing@axl",      "BROADBAND FIBRENET",        1700, 140, 12,  799),
    ("cloudnote.sub@ybl",         "CLOUDNOTE SUBSCRIPTION",    1050, 200, 12,  199),
    ("sipautosave@ybl",           "SIP AUTOSAVE PLAN",         1400,  90, 12, 2500),
    # People. Few payers, but the ones there are keep coming back.
    ("ramanarao.k@oksbi",         "K RAMANA RAO",               900,   4, 12, 18500),
    ("raviteja.k@oksbi",          "RAVI TEJA K",                700,   9,  6,   300),
    ("sneha.p@ybl",               "SNEHA P",                    650,  11,  5,   250),
    ("arjun.m@paytm",             "ARJUN M",                    720,   8,  6,   200),
    ("deepthi.r@axl",             "DEEPTHI R",                  680,  10,  5,   350),

    # The planted ones. Young, wide and shallow: many payers, none returning.
    ("quickcash.agency@fastpay",  "QUICKCASH AGENCY",             3,  42,  1,  4500),
    ("nehru.traders99@fastpay",   "NEHRU TRADERS ENTERPRISE",     6,   2,  1, 61000),
    ("rk.supplies77@fastpay",     "RK GENERAL SUPPLIES",          5,   3,  1, 38750),
    ("electricity.billdesk@upiservice", "ELECTRICITY BILL DESK",   4,   9,  1, 12500),
    ("hdfcbank.refund@yb1",       "HDFC BANK REFUND CELL",        11,   5,  1, 39000),
]
PAYEE_CROWD += [(f"verify0{i}@quickpay", f"VERIFY0{i} SERVICES", 1, 1, 1, 12)
                for i in range(1, 9)]


def write_seed(path: Path) -> None:
    payload = {
        "note": ("Counterparty crowd for docs/demo/DEMO_UPI_Statement.pdf. "
                 "Ages are in days before the moment of loading, so the file "
                 "does not go stale. Load with: python "
                 "scripts/bootstrap_payee_reputation.py --demo-statement"),
        "payees": [
            {"vpa": v, "display_name": n, "age_days": a,
             "other_payers": p, "payments_each": e, "typical_amount": amt}
            for v, n, a, p, e, amt in PAYEE_CROWD
        ],
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


# ── Rendering ────────────────────────────────────────────────────────────────

def render_pdf(rows: list[Tx], path: Path, rng: random.Random) -> int:
    for name, file in FONTS.items():
        pdfmetrics.registerFont(TTFont(name, str(file)))

    W, H = A4
    c = canvas.Canvas(str(path), pagesize=A4)
    left, right = 18 * mm, W - 18 * mm
    pages = 0

    def banner():
        c.setFillColorRGB(0.75, 0.15, 0.15)
        c.setFont("Demo-Bold", 7)
        c.drawCentredString(W / 2, H - 10 * mm, BANNER)
        c.setFillColorRGB(0, 0, 0)

    def header(first: bool) -> float:
        nonlocal pages
        pages += 1
        banner()
        y = H - 22 * mm
        if first:
            c.setFont("Demo-Bold", 14)
            c.drawString(left, y, f"Transaction Statement for {ACCOUNT}")
            y -= 6 * mm
            c.setFont("Demo", 9.5)
            c.drawString(left, y, f"{START:%d %b, %Y} - {END:%d %b, %Y}")
            y -= 4 * mm
            c.setFont("Demo", 8)
            c.drawString(left, y, "PhonePe statement layout (synthetic sample for testing a parser)")
            y -= 8 * mm
        c.setFillColorRGB(0.96, 0.96, 0.97)
        c.rect(left, y - 2 * mm, right - left, 7 * mm, fill=1, stroke=0)
        c.setFillColorRGB(0.35, 0.35, 0.40)
        c.setFont("Demo-Bold", 9)
        c.drawString(left + 2 * mm, y, "Date")
        c.drawString(left + 34 * mm, y, "Transaction Details")
        c.drawString(right - 44 * mm, y, "Type")
        c.drawRightString(right - 2 * mm, y, "Amount")
        c.setFillColorRGB(0, 0, 0)
        return y - 9 * mm

    def footer():
        c.setFont("Demo", 7.5)
        c.setFillColorRGB(0.45, 0.45, 0.45)
        c.drawCentredString(W / 2, 14 * mm, f"Page {pages}")
        c.drawCentredString(W / 2, 10 * mm,
                            "Generated test data. No real account, card or person is represented.")
        c.setFillColorRGB(0, 0, 0)

    y = header(first=True)
    for tx in rows:
        if y < 34 * mm:
            footer()
            c.showPage()
            y = header(first=False)

        credit = tx.direction == "CREDIT"
        verb = "Received from" if credit else "Paid to"

        c.setFont("Demo", 8.5)
        c.setFillColorRGB(0.25, 0.25, 0.30)
        c.drawString(left + 2 * mm, y, f"{tx.when:%b %d, %Y}")
        c.drawString(left + 2 * mm, y - 4.2 * mm, f"{tx.when:%I:%M %p}")
        c.setFillColorRGB(0, 0, 0)

        c.setFont("Demo-Bold", 9)
        c.drawString(left + 34 * mm, y, f"{verb} {tx.counterparty}")
        c.setFont("Demo", 7.8)
        c.setFillColorRGB(0.42, 0.42, 0.47)
        c.drawString(left + 34 * mm, y - 4.2 * mm, f"UPI ID: {tx.vpa}")
        c.drawString(left + 34 * mm, y - 8.0 * mm,
                     f"Transaction ID T{tx.when:%y%m%d}{_ref(rng, '', 14)}")
        c.drawString(left + 34 * mm, y - 11.8 * mm, f"UTR No. {_ref(rng, '', 12)}")
        tail = f"{'Credited to' if credit else 'Paid by'}  {CARD_TAIL}"
        if tx.autopay:
            tail += "   AUTOPAY"
        c.drawString(left + 34 * mm, y - 15.6 * mm, tail)
        c.setFillColorRGB(0, 0, 0)

        c.setFont("Demo-Bold", 8.5)
        if credit:
            c.setFillColorRGB(0.05, 0.55, 0.30)
        c.drawString(right - 44 * mm, y, tx.direction)
        c.setFont("Demo-Bold", 9.5)
        c.drawRightString(right - 2 * mm, y, f"₹{tx.amount:,.2f}".rstrip("0").rstrip("."))
        c.setFillColorRGB(0, 0, 0)

        c.setStrokeColorRGB(0.90, 0.90, 0.92)
        c.line(left, y - 19 * mm, right, y - 19 * mm)
        y -= 23 * mm

    footer()
    c.save()
    return pages


def write_csv(rows: list[Tx], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["timestamp", "counterparty", "upi_id", "amount", "direction",
                    "planted_scenario", "expected_signal"])
        for tx in rows:
            w.writerow([tx.when.strftime("%Y-%m-%d %H:%M:%S"), tx.counterparty, tx.vpa,
                        f"{tx.amount:.2f}", tx.direction, tx.planted, "; ".join(tx.tags)])


def write_key(rows: list[Tx], pages: int, path: Path) -> None:
    fraud = [t for t in rows if t.planted]
    legit = [t for t in rows if not t.planted]
    spend = sorted(t.amount for t in legit if t.direction == "DEBIT")
    median = spend[len(spend) // 2]

    blocks = {
        "F1": ("Probe burst",
               "A credential being tested. Eight payments of Rs 1 to Rs 47 to eight "
               "addresses never paid before, inside 24 minutes, starting 02:14.",
               "Transaction Scoring. Velocity, the night hour and an all-new payee set "
               "fire together. On the Network Graph these show as eight one-shot leaves "
               "appearing off the payer at once."),
        "F2": ("Funnel account",
               "One address opened three days earlier takes 5 x Rs 4,500 in 44 minutes "
               "and sends nothing back.",
               "The strongest catch in the file, and it comes entirely from the payee "
               "side: 42 other payers, none of whom returned, into an address three days "
               "old. The payer behaves normally throughout. This is the row to use when "
               "someone asks why the payee half of the model is there."),
        "F3": ("Hijacked profile",
               "Rs 92,400 at 03:47 to an address never paid before - far above anything "
               "this payer sends, at an hour they have never used.",
               "Transaction Scoring. Amount against the payer's own median, hour "
               "familiarity and an unseen payee. The amount also sits above 70% of the "
               "per-transaction ceiling, which the amount check reports separately."),
        "F4": ("Victim-authorised transfer",
               "Rs 18,000 at 11:32 on an ordinary day, preceded by a Rs 1 credit from the "
               "same address thirteen minutes earlier - the refund-scam opening, a token "
               "payment to prove the 'refund' works before the real ask.",
               "EXPECTED TO SCORE LOW, and worth showing for that reason. Nothing about "
               "the payment is unusual, because in this class nothing ever is: the payer "
               "authorised it themselves after being deceived. The report measures 28.6% "
               "recall here. What covers it is the payee check (address four days old, "
               "nine payers, none returning) and the coercion classifier if the message "
               "is pasted in."),
        "F5": ("Lookalike bank handle",
               "Rs 47,500 to hdfcbank.refund@yb1. The handle is @yb1 with a digit one; "
               "the real handle is @ybl with a letter ell. In the face every payment app "
               "renders a VPA in, they are all but identical.",
               "Payee Check scores this 100 on two separate critical findings: the "
               "confusable handle, and a bank's name paired with the word 'refund', which "
               "no bank handle does. The behavioural model cannot see any of it - no "
               "feature in the model reads the characters of an address."),
    }

    lines = [
        "# Demo statement - answer key",
        "",
        "Built by `scripts/make_demo_statement.py`. Every row is synthetic. No real",
        "account, card, phone number or person appears anywhere in it, and the file says",
        "so on every page.",
        "",
        "## Before you demo",
        "",
        "```",
        "python scripts/make_demo_statement.py                              # build it",
        "python scripts/bootstrap_payee_reputation.py --demo-statement      # seed payees",
        "python scripts/verify_demo_statement.py                            # check it",
        "```",
        "",
        "The verifier scores every row below through the real model and prints what a",
        "judge will see. Run it the morning of the demo. It exits non-zero if anything",
        "has moved.",
        "",
        "The seeding step is not optional. A statement is one payer's side of every edge;",
        "it cannot say how many *other* people paid an address or whether any came back,",
        "and those two facts are what separate a busy shop from a collection account.",
        "Without the seed the funnel account scores like any other new payee.",
        "",
        "## What is in the file",
        "",
        f"- Period: the 92 days ending the day it was generated",
        f"- {len(rows)} rows over {pages} pages: {len(legit)} ordinary, {len(fraud)} planted",
        f"- Median ordinary payment: Rs {median:,.0f}",
        "- Persona: salaried, pays rent monthly, buys groceries, takes cabs, has four",
        "  friends who pay them back and an employer who pays them",
        "",
        "The ordinary traffic is doing work, not filling pages. The engine scores a",
        "payment against the payer's *own* history, so without three months of habits",
        "none of the planted rows would stand out. Two choices in it matter:",
        "",
        "- **The monthly rent is five figures.** So a large amount is normal for this",
        "  payer, and F3 has to be caught on who is being paid and when, not on size.",
        "- **Almost nothing happens at night.** Nine night-window rows in three months,",
        "  and eight of them are the planted burst. That is what makes 02:14 loud.",
        "",
        "## The planted rows",
        "",
    ]
    for code, (title, what, expect) in blocks.items():
        hits = [t for t in fraud if t.planted == code]
        when = min(t.when for t in hits)
        total = sum(t.amount for t in hits if t.direction == "DEBIT")
        lines += [
            f"### {code} - {title}",
            "",
            f"**{when:%d %b %Y, %I:%M %p}** &middot; {len(hits)} row(s) &middot; Rs {total:,.0f}",
            "",
            f"{what}",
            "",
            f"*What fires:* {expect}",
            "",
        ]

    lines += [
        "## Suggested order for a demo",
        "",
        "1. **Import the statement.** The payer profile builds from the ordinary traffic.",
        "   Show the profile: median payment, usual hour, the handful of payees they",
        "   actually deal with.",
        "2. **Open the Network Graph.** The regular payees form a small dense core. F1's",
        "   eight one-shot leaves and F2's funnel sit outside it and are visible without",
        "   anyone explaining them.",
        "3. **Score F3.** A strong, obvious catch. Good confidence-builder.",
        "4. **Run F5's address through Payee Check.** Show @yb1 beside @ybl on screen and",
        "   let the panel try to tell them apart. Then point out the model scored it on",
        "   behaviour alone and never looked at the characters at all.",
        "5. **Score F4 last, and say it scores low.** Then show the payee check and the",
        "   coercion classifier picking it up. A panel told plainly where a system is",
        "   weak, and shown the design that covers that weakness, will believe the parts",
        "   that work. A panel that catches you overselling will not.",
        "",
        "## Deliberately not in the file",
        "",
        "- **An amount over the Rs 1,00,000 ceiling.** It cannot appear in a real",
        "  statement because the rail rejects it before settlement. Demonstrate that",
        "  check by typing Rs 1,50,000 into Transaction Scoring directly.",
        "- **A scam message.** The coercion classifier takes pasted text, not statement",
        "  rows. Paste something in the style of \"your electricity will be disconnected",
        "  tonight, pay now to avoid it\" while F4 is on screen.",
        "",
        "## If a judge asks whether the data is real",
        "",
        "Say no, and say why: UPI transaction records identify both parties, so no",
        "labelled public dataset exists and a real statement cannot be shown. The",
        "generator is in the repository and its parameters are in the report. That answer",
        "is stronger than a vague one, and it is the same limitation the report states in",
        "its own results chapter.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rng = random.Random(SEED)
    OUT.mkdir(parents=True, exist_ok=True)

    rows = legitimate(rng) + planted()
    rows.sort(key=lambda t: t.when, reverse=True)   # newest first, as wallets print

    pdf = OUT / "DEMO_UPI_Statement.pdf"
    pages = render_pdf(rows, pdf, rng)
    write_csv(rows, OUT / "DEMO_UPI_Statement.csv")
    write_seed(OUT / "DEMO_PAYEE_SEED.json")
    write_key(rows, pages, OUT / "DEMO_ANSWER_KEY.md")

    fraud = sum(1 for t in rows if t.planted)
    print(f"  {len(rows)} rows ({len(rows) - fraud} ordinary, {fraud} planted) "
          f"over {pages} pages")
    print(f"  written: {pdf.relative_to(ROOT)}")
    print(f"           {(OUT / 'DEMO_UPI_Statement.csv').relative_to(ROOT)}")
    print(f"           {(OUT / 'DEMO_PAYEE_SEED.json').relative_to(ROOT)}")
    print(f"           {(OUT / 'DEMO_ANSWER_KEY.md').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
